# Generated by Django 4.2.2 on 2025-03-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Enter a person name", max_length=200),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="Enter the person surname", max_length=200
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
