# Generated by Django 4.2.2 on 2025-03-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="persona",
            old_name="surname",
            new_name="apellido",
        ),
        migrations.RenameField(
            model_name="persona",
            old_name="name",
            new_name="nombre",
        ),
        migrations.AlterField(
            model_name="persona",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
